name = "storyhouse-vip"
compatibility_date = "2024-06-07"
pages_build_output_dir = "apps/frontend/.vercel/output/static"

# Environment variable bindings will be configured in Cloudflare dashboard
# Including:
# - OPENAI_API_KEY
# - R2_ACCESS_KEY_ID  
# - R2_SECRET_ACCESS_KEY
# - R2_BUCKET_NAME
# - R2_ENDPOINT
# - R2_PUBLIC_URL
# - STORY_PROTOCOL_*
# - NEXT_PUBLIC_*