name = "storyhouse-vip"
compatibility_date = "2024-06-07"
pages_build_output_dir = "apps/frontend/.next"

# Environment configurations
[env.production]
vars = { NODE_ENV = "production" }

[env.staging]
vars = { NODE_ENV = "staging" }

[env.development]
vars = { NODE_ENV = "development" }

# Build configuration
[build]
command = "npm run build"
cwd = "."

# Cloudflare Pages specific settings
[pages]
# Enable compatibility with Next.js App Router
compatibility_flags = ["nodejs_compat"]

# Function configuration for API routes
[functions]
# Increase timeout for AI generation endpoints
max_duration = 30000  # 30 seconds (Cloudflare Pages limit)

# Environment variable bindings will be configured in Cloudflare dashboard
# Including:
# - OPENAI_API_KEY
# - R2_ACCESS_KEY_ID  
# - R2_SECRET_ACCESS_KEY
# - R2_BUCKET_NAME
# - R2_ENDPOINT
# - R2_PUBLIC_URL
# - STORY_PROTOCOL_*
# - NEXT_PUBLIC_*