[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
cache_path = "cache"

# Solidity compiler settings
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = true

# Testing settings
verbosity = 2
fuzz = { runs = 1000 }
invariant = { runs = 256, depth = 15 }

# Gas settings
gas_reports = ["*"]
gas_reports_ignore = ["test/**/*"]

# Formatter settings
line_length = 120
tab_width = 4
bracket_spacing = false
int_types = "long"

# RPC endpoints
[rpc_endpoints]
story_testnet = "https://aeneid.storyrpc.io"
localhost = "http://localhost:8545"

# Etherscan API keys (for verification)
[etherscan]
story_testnet = { key = "${ETHERSCAN_API_KEY}", chain = 1315, url = "https://aeneid.storyscan.xyz/api" }

# Remappings for dependencies
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@story-protocol/=lib/story-protocol/",
    "forge-std/=lib/forge-std/src/",
]

# Profile for CI
[profile.ci]
fuzz = { runs = 10000 }
invariant = { runs = 1000, depth = 20 }

# Profile for intense testing
[profile.intense]
fuzz = { runs = 50000 }
invariant = { runs = 2000, depth = 25 }
