# StoryHouse Smart Contracts - Foundry Configuration
# This project uses Foundry as the primary smart contract development framework
# See packages/contracts/README.md for complete development guide

[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
cache_path = "cache"

# Solidity compiler settings
solc = "0.8.20"
optimizer = true
optimizer_runs = 200

# Testing settings
verbosity = 2
gas_reports = ["*"]

# Exclude legacy scripts from compilation
exclude = ["script/legacy/**/*"]

# V2 deployment profile - excludes contracts with missing dependencies
[profile.v2]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
cache_path = "cache"
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
# Exclude contracts that depend on removed RewardsManager
exclude = [
    "src/HybridRevenueController.sol",
    "src/ChapterAccessController.sol", 
    "src/HybridRevenueControllerV2.sol",
    "script/Deploy.s.sol",
    "script/DeployChapterAccess.s.sol",
    "script/DeployHybridRevenueController.s.sol",
    "script/DeployRewardsManager.s.sol",
    "test/**/*"
]

# Remappings for dependencies
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/",
]

[fuzz]
runs = 1000

# RPC endpoints
[rpc_endpoints]
story_testnet = "https://aeneid.storyrpc.io"
localhost = "http://localhost:8545"
